export enum ArtworkStatus {
    RESERVED = 'RESERVED',
    VISITED = 'VISITED',
    DRYING = 'DRYING',
    BISQUE_FIRING = 'BISQUE_FIRING',
    GLAZING = 'GLAZING',
    GLAZE_FIRING = 'GLAZE_FIRING',
    COMPLETED = 'COMPLETED',
    CANCELED = 'CANCELED',
}
